# -*- coding: utf-8 -*-
"""AI-2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6b8Af1zsCZAZSP4-jy8bNZa8XpkoKjN
"""

import pandas as pd
# Para manipulación de datos
import numpy as np
# Para cálculos numéricos
import matplotlib.pyplot as plt
# Para generar gráficos
from time import time
# Para medir duración del entrenamiento
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVR
# Algoritmo de regresión SVR
from sklearn.metrics import r2_score
# Métrica para evaluar el modelo
from google.colab import files
# Para subir archivos en Google Colab, como lo estaba haciendo no me dejaba y tambien se podia de esta forma
import io
# Para leer el archivo cargado

# 1. CARGA DEL DATASET NORMALIZADO
print("🔍 Cargando dataset normalizado...")
uploaded = files.upload()
# Subir archivo CSV

file_name = list(uploaded.keys())[0]
# Obtener el nombre del archivo subido
df = pd.read_csv(io.BytesIO(uploaded[file_name]))
# Leer archivo como DataFrame

print(f"Dt cargado con {df.shape[0]} filas y {df.shape[1]} columnas")
print("\nPrimeras 5 filas del dataset:")
print(df.head())
# Mostrar primeras filas del dataset

# 2. DEFINIR X e y O LA DEFINICION DE NUESTRAS VARIABLES
print("\n Preparando variables para el modelo...")
X = df.drop('quality', axis=1)
# Variables de entrada (todas menos 'quality')
y = df['quality']
# Variable objetivo: calidad del vino

print(f"Variables de entrada (X): {X.shape[1]} características")
print(f"variable objetivo (y): quality")

# 3. DIVISIÓN DE DATOS (80% ENTRENAMIENTO, 20% PRUEBA)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"\n Conjunto de entrenamiento: {X_train.shape[0]} muestras")
print(f"Conjunto de prueba: {X_test.shape[0]} muestras")

# 4. MODELADO CON SVR Y OPTIMIZACIÓN DE HIPERPARÁMETROS
param_grid = {
    'kernel': ['linear', 'rbf'],
# Elege los 2 kernels más representativos
    'C': [1, 10],
# Eliminamos extremos o son los valores razonables de penalización
    'epsilon': [0.1, 0.5]
# Solo 2 valores o es el margen de tolerancia para el error
}


print("búsqueda de hiperparámetros óptimos...")
print("   Esto puede tardar varios minutos...")
# Inicia búsqueda con validación cruzada
start_time = time()
grid = GridSearchCV(SVR(), param_grid, cv=5, scoring='r2', n_jobs=-1, verbose=1)
grid.fit(X_train, y_train)
training_time = time() - start_time

print(f"\nEntrenamiento completado en {training_time:.2f} segundos")

# 5. MEJORES HIPERPARÁMETROS ENCONTRADOS
best_params = grid.best_params_
print("\n MEJORES HIPERPARÁMETROS ENCONTRADOS:")
print(f"   - Kernel: {best_params['kernel']}")
print(f"   - C: {best_params['C']}")
print(f"   - Epsilon: {best_params['epsilon']}")

# 6. EVALUACIÓN DEL MODELO
print("\nEvaluando modelo con datos de prueba...")
best_model = grid.best_estimator_
y_pred = best_model.predict(X_test)

# Calculando R² score
r2 = r2_score(y_test, y_pred)
# Calcular R²
print(f"\n R² SCORE: {r2:.4f}")

plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred, alpha=0.6, color='blue', label='Predichos')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', label='Línea perfecta')
plt.xlabel("Valores reales")
plt.ylabel("Valores predichos")
plt.title("Valores reales vs. predichos - SVR")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("valores_reales_vs_predichos.png")
plt.show()

#Gráfica por índice
cantidad_probar = min(300, len(y_test))
# Muestra solo las primeras 300 muestras
X_axis = np.arange(cantidad_probar)
plt.figure(figsize=(10, 6))
plt.scatter(X_axis, y_test.iloc[:cantidad_probar].values, label="Reales", alpha=0.6)
plt.scatter(X_axis, y_pred[:cantidad_probar], label="Predichos", alpha=0.6)
plt.title("Comparación por índice - Valores Reales vs. Predichos")
plt.xlabel("Índice de muestra")
plt.ylabel("Calidad (normalizada)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("comparacion_indice_reales_vs_predichos.png")
plt.show()