# -*- coding: utf-8 -*-
"""Parcial2-IA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6b8Af1zsCZAZSP4-jy8bNZa8XpkoKjN
"""

# Importación de librerías necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import MinMaxScaler, LabelEncoder, OneHotEncoder
from sklearn.svm import SVR
from sklearn.metrics import r2_score
from sklearn.impute import SimpleImputer
import seaborn as sns

# 1. Cargamos el dataset
print("1. CARGANDO EL DATASET") #Auto MPG Dataset de UCI Repository
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data"
# url -> enlace del dt
nombres_columnas = ['consumo',
                    'cilindros', 'cilindrada', 'potencia', 'peso','aceleracion', 'año_modelo', 'origen',
                    'nombre_auto']
#nombres_columas  -> las variables en español para poder comprender mejor
#elimine nombre_Auto (categorica) no sirve para predecir el consumo
#potencia tiene valores ? (6 registros)
datos = pd.read_csv(url, delim_whitespace=True, names=nombres_columnas)
#pd.read_csv carga el archivo por espacios

# Muestra las primeras 5 filas para entender la estructura
print("\nPrimeras filas del dataset:")
print(datos.head())

# Información general (tipos de datos y valores no nulos)
print("\nInformación del dataset:")
print(datos.info())

# (media, desviación estándar, etc.)
print("\nEstadísticas descriptivas:")
print(datos.describe())

# Cuenta valores faltantes por columna
print("\nValores faltantes por columna:")
print(datos.isnull().sum())

# Verifica valores únicos en columnas categóricas
print("\nValores únicos en columnas categóricas:")
print("Origen:", datos['origen'].unique())
print("Año del modelo:", datos['año_modelo'].unique())

# 2. Preprocesamiento de los datos
print("\n2. PREPROCESAMIENTO DE LOS DATOS")

# 2.1 Eliminamos la columna 'nombre_auto' ya que esta no es relevante para la predicción
datos = datos.drop('nombre_auto', axis=1)
print("\nColumnas después de eliminar 'nombre_auto':", datos.columns.tolist())

# 2.2 Identificamos y reemplazamos valores '?' que indican valores faltantes
print("\nVerificar si hay valores '?' en el dataset:")
for columna in datos.columns:
    valores_faltantes = (datos[columna] == '?').sum()
    if valores_faltantes > 0:
        print(f"La columna {columna} tiene {valores_faltantes} valores '?'")
# Reemplazamos '?' con NaN para facilitar el manejo de datos faltantes
datos = datos.replace('?', np.nan)

# Convertimos columnas a tipos numéricos (donde algunas podrían ser strings por los valores '?')
for columna in datos.columns:
    if columna != 'origen':  # Solo convertimos las columnas numéricas
        datos[columna] = pd.to_numeric(datos[columna], errors='coerce')

print("\nValores faltantes después de la conversión:")
print(datos.isnull().sum())

# 2.3 Imputamos los valores faltantes para columnas numéricas
columnas_con_nulos = datos.columns[datos.isnull().any()].tolist()
if columnas_con_nulos:
    print(f"\nImputando valores faltantes en columnas: {columnas_con_nulos}")
    for columna in columnas_con_nulos:
        if columna != 'origen':  # Solo imputamos columnas numéricas
            imputador = SimpleImputer(strategy='mean')
            datos[[columna]] = imputador.fit_transform(datos[[columna]])

print("\nValores faltantes después de la imputación:")
print(datos.isnull().sum())

# 2.4 Convertimos las variables categóricas a numéricas
# La columna 'origen' es categórica (1 = USA, 2 = Europa, 3 = Asia)
print("\nConvirtiendo variable categórica 'origen' con OneHotEncoder:")
try:
    # Para versiones recientes de scikit-learn (>=1.2) y la otra es pa versiones anteriores
    codificador = OneHotEncoder(sparse_output=False, drop='first')
    origen_codificado = codificador.fit_transform(datos[['origen']])
except TypeError:

    codificador = OneHotEncoder(sparse=False, drop='first')
    origen_codificado = codificador.fit_transform(datos[['origen']])

# Creamos el DataFrame con las variables codificadas
origen_df = pd.DataFrame(origen_codificado, columns=['origen_europa', 'origen_asia'])
# Combinamos el DataFrame original (sin 'origen') con las nuevas columnas
datos = pd.concat([datos.drop('origen', axis=1), origen_df], axis=1)

print("\nColumnas después de la codificación one-hot:")
print(datos.columns.tolist())

# 2.5 Normalización de las variables numéricas entre 0 y 1
print("\nNormalizando variables numéricas con MinMaxScaler:")
# Seleccionamos la variable objetivo y las características
y_objetivo = datos['consumo']  # Variable objetivo: consumo de combustible en millas por galón
X_caracteristicas = datos.drop('consumo', axis=1)

# Aplicamos MinMaxScaler para normalizar las características
normalizador = MinMaxScaler()
X_normalizado = normalizador.fit_transform(X_caracteristicas)
X_normalizado_df = pd.DataFrame(X_normalizado, columns=X_caracteristicas.columns)

# Mostramos los datos después del preprocesamiento
print("\nDatos después del preprocesamiento (primeras 5 filas):")
print(X_normalizado_df.head())

# 3. División de datos en conjuntos de entrenamiento y prueba
print("\n3. DIVISIÓN DE DATOS EN CONJUNTOS DE ENTRENAMIENTO Y PRUEBA")
X_entrenamiento, X_prueba, y_entrenamiento, y_prueba = train_test_split(
    X_normalizado, y_objetivo, test_size=0.2, random_state=42)

print(f"X_entrenamiento: {X_entrenamiento.shape}")
print(f"X_prueba: {X_prueba.shape}")
print(f"y_entrenamiento: {y_entrenamiento.shape}")
print(f"y_prueba: {y_prueba.shape}")

# 4. Modelado con SVR y optimización de hiperparámetros con GridSearchCV
print("\n4. MODELADO CON SVR Y OPTIMIZACIÓN DE HIPERPARÁMETROS")
# Definir los hiperparámetros a probar
parametros_a_probar = {
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
    'C': [0.1, 1, 10, 100],
    'epsilon': [0.01, 0.1, 0.2, 0.5]
}

# Creamos: Modelo SVR
modelo_svr = SVR()

# Objeto GridSearchCV
buscador_parametros = GridSearchCV(modelo_svr, parametros_a_probar, cv=5,
                                  scoring='r2', n_jobs=-1, verbose=1)

# Entrenamos el modelo con GSCV
print("\nEntrenando modelo con GridSearchCV (esto puede tardar unos minutos)...")
buscador_parametros.fit(X_entrenamiento, y_entrenamiento)

# Mejores hiperparámetros encontrados
print("\nMejores hiperparámetros encontrados:")
print(buscador_parametros.best_params_)

# El mejor modelo
mejor_modelo = buscador_parametros.best_estimator_

# 5. Evaluación del modelo y calculamos el coeficiente de determinacion R²
print("\n5. EVALUACIÓN DEL MODELO")
# Realizar predicciones en el conjunto de prueba
y_predicciones = mejor_modelo.predict(X_prueba)

# R²
r2 = r2_score(y_prueba, y_predicciones)
print(f"\nR² score en el conjunto de prueba: {r2:.4f}")

# Indices para el gráfico
indices = range(len(y_prueba))

#Scatter plot de valores reales vs predichos
plt.figure(figsize=(12, 8))
plt.scatter(indices, y_prueba, color='orange', alpha=0.8, s=70, label='Valores reales (y_prueba)')
plt.scatter(indices, y_predicciones, color='blue', alpha=0.6, s=40, label='Valores predichos (y_predicciones)')

#Figura
plt.savefig('comparacion_real_vs_predicho.png', dpi=300)
plt.show()

# Análisis de residuos
plt.figure(figsize=(10, 6))
errores = y_prueba - y_predicciones
plt.scatter(y_predicciones, errores, color='green', alpha=0.5)
plt.axhline(y=0, color='r', linestyle='-')
plt.xlabel('Valores predichos', fontsize=12)
plt.ylabel('Errores', fontsize=12)
plt.title('Análisis de errores', fontsize=14)
plt.grid(True)
plt.savefig('analisis_errores.png', dpi=300)
plt.show()

# Histograma de residuos
plt.figure(figsize=(10, 6))
plt.hist(errores, bins=20, color='purple', alpha=0.7)
plt.axvline(x=0, color='r', linestyle='-')
plt.xlabel('Errores', fontsize=12)
plt.ylabel('Frecuencia', fontsize=12)
plt.title('Distribución de errores', fontsize=14)
plt.grid(True)
plt.savefig('distribucion_errores.png', dpi=300)
plt.show()

# 6. Resumen final
print("\n=== RESUMEN FINAL ===")
print(f"Mejor modelo: SVR con kernel {mejor_modelo.kernel}")
print(f"Valor de C: {mejor_modelo.C}")
print(f"Valor de epsilon: {mejor_modelo.epsilon}")
print(f"Puntuación R²: {r2:.4f}")
print("=====================")